[package]
name = "axum-updatable"
version = "0.1.0"
authors = ["Oleks Pickle <olekspickle@users.noreply.github.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.69"
axum = "0.6.9"
lazy_static = "1.4.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tinytemplate = "1.2.1"
tokio = { version = "1.26", default-features = false, features = ["macros", "rt-multi-thread", "time"] }
tower = { version = "0.4", features = ["util", "timeout", "load-shed", "limit"] }
tower-http = { version = "0.4.0", features = [
    "add-extension",
    "auth",
    "compression-full",
    "limit",
    "trace",
] }
tower-layer = "0.3.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
