[package]
name = "axum-template"
version = "0.1.0"
authors = ["Oleks Pickle <olekspickle@users.noreply.github.com>"]
edition = "2021"

[dependencies]
askama = "0.11"
axum = "0.6.15"
serde = "1.0.160"
serde_json = "1.0.96"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["fs", "trace"]}
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
